#Minttu Lindholm 7.11.2019
##Data wrangling

**The data**

``` {r}
library(dplyr)

lrn14 <- read.table("http://www.helsinki.fi/~kvehkala/JYTmooc/JYTOPKYS3-data.txt", sep="\t", header=TRUE)
dim(lrn14)
str(lrn14)
```
The data has `r dim(lrn14)` and `r str(lrn14)`.

**Creating the analysis data set**

```{r}
deep_questions <- c("D03", "D11", "D19", "D27", "D07", "D14", "D22", "D30","D06",  "D15", "D23", "D31")
surface_questions <- c("SU02","SU10","SU18","SU26", "SU05","SU13","SU21","SU29","SU08","SU16","SU24","SU32")
strategic_questions <- c("ST01","ST09","ST17","ST25","ST04","ST12","ST20","ST28")

deep_columns <- select(lrn14, one_of(deep_questions))
lrn14$deep <- rowMeans(deep_columns)
surface_columns <- select(lrn14, one_of(surface_questions))
lrn14$surf <- rowMeans(surface_columns)
strategic_columns <- select(lrn14, one_of(strategic_questions))
lrn14$stra <- rowMeans(strategic_columns)

keep_columns <- c("gender","Age","Attitude", "deep", "stra", "surf", "Points")

learning2014 <- select(lrn14, one_of(keep_columns))

lrn14$attitude <- lrn14$Attitude / 10

learning2014 <- filter(learning2014, Points > 0) 
str(learning2014)
```
**Saving the analysis dataset**

```{r}
write.csv(learning2014, "create_learning2014.csv")
read.csv("create_learning2014.csv", TRUE, ",")
```